### ISSUE TITLE
some overcomplicated API uses :)

### ISSUE THREAD

**Issue by jakubmisek** [petrsvihlik/Kentico.Kontent.Delivery.PeachPie#1]
like in here
 https://github.com/petrsvihlik/PeachPieTests/blob/abc8f4c6e1a433091464180006239fe596812f08/kc-peachpie-test/PeachPieTests.cs#L66 

`result.ToClr(typeof(T)) as T` should be replaced with
`(T)result.ToClr()` or
`(T)result.AsObject()` // fastest

There are some useful implicit conversions between C# values and PhpValue https://docs.peachpie.io/api/ref/phpvalue/

Also it would help if your API would have strongly-typed setters and getters.

**Comment by petrsvihlik** [comment]
cool, thanks for the suggestions :)

**Comment by petrsvihlik** [comment]
fixed

**Comment by petrsvihlik** [comment]
>Also it would help if your API would have strongly-typed setters and getters.

what did you mean by this btw? to have strongly-typed setters and getters in the PHP classes? that won't be possible until PHP 7.4... both `ContentType` and `ContentTypeSystem` that I use in my code are originally PHP classes that are compiled by peachpie.
